python("import sys; import os");
python("SHELF_DIR = os.environ.get('MAYA_SHELF_DIR')");
python("sys.path.append(SHELF_DIR)");
python("import byu_shelf");

//Test
python("print '##############TEST##############'");
python("import maya.cmds");
python("cmds.loadPlugin('/users/guest/t/tcbarrus/taijitu/byu-pipeline-tools/maya-tools/plug-ins/cvshapeinverter_plugin.py')");
python("print '##############END TEST##############'");
